import type {
  Constraint,
  ExtractedSpec,
  Model,
  Property,
} from "../extract/types.ts";

/**
 * Pure assertion generator — turns an extracted spec into the text of
 * `.verbo/validate.ts`, which checks value-level constraints that TypeScript
 * types cannot express (DESIGN §8). The generated module is `deno check`-clean
 * and runnable: CI imports the per-model `validate<Model>(value)` functions.
 *
 * For every constrained property it emits an `assert_<Model>_<prop>(value,
 * source)` function that throws on violation (DESIGN §8.2), and per model a
 * `validate<Model>(value)` function that runs all its assertions and returns
 * the list of violation messages (empty when clean).
 *
 * Constraints are sanitized against the property type so the output always
 * type-checks: numeric constraints (range/minimum/maximum/positive) only on
 * `number`, enum only on `string`/`number`, format only on `string`.
 * Incompatible constraints are skipped, not asserted.
 */

const HEADER = "// .verbo/validate.ts — generated by Verbo, do not edit.";

export function generateAssertions(spec: ExtractedSpec): string {
  const importedModels: string[] = [];
  const blocks: string[] = [];

  for (const model of spec.models) {
    const assertFns: string[] = [];
    const calls: string[] = [];

    for (const property of model.properties) {
      const applicable = applicableConstraints(property);
      if (applicable.length === 0) continue;

      // One merged assert function per property (handles multiple constraints,
      // e.g. `minimum` + `positive`, without duplicate declarations).
      assertFns.push(renderAssert(model, property, applicable));

      const prop = property.name;
      const call =
        `run(() => assert_${model.name}_${prop}(value.${prop}, "${model.name}.${prop}"), violations)`;
      if (property.optional) {
        calls.push(`  if (value.${prop} !== undefined) {`);
        calls.push(`    ${call};`);
        calls.push(`  }`);
      } else {
        calls.push(`  ${call};`);
      }
    }

    if (calls.length === 0) continue;

    importedModels.push(model.name);
    blocks.push(
      ...assertFns,
      renderValidate(model.name, calls),
    );
  }

  if (blocks.length === 0) return `${HEADER}\n`;

  const importLine = `import type { ${
    importedModels.join(", ")
  } } from "../types.verbo.ts";`;

  const runHelper = [
    "/** Run one assertion, collecting its failure message instead of throwing. */",
    "function run(assert: () => void, violations: string[]): void {",
    "  try {",
    "    assert();",
    "  } catch (err) {",
    "    violations.push((err as Error).message);",
    "  }",
    "}",
  ].join("\n");

  return [
    HEADER,
    "",
    importLine,
    "",
    runHelper,
    "",
    blocks.join("\n\n"),
    "",
  ].join("\n");
}

// --- Assertion functions ---

/** One `assert_<Model>_<prop>` per constrained property. Multiple constraints
 * on the same property are merged into that single function (in order) so the
 * generated file never declares a name twice. */
function renderAssert(
  model: Model,
  property: Property,
  constraints: Constraint[],
): string {
  const fnName = `assert_${model.name}_${property.name}`;
  const prop = property.name;
  const sourceHint = model.source ?? "spec";
  const desc = constraints.map(describeConstraint).join(", ");

  const hasRequired = constraints.some((c) => c.kind === "required");
  // `required` needs to accept any value (a missing value may arrive from
  // untyped runtime data), so the parameter becomes `unknown` and typed checks
  // cast. Otherwise the parameter is the property's exact scalar type.
  const valueType = hasRequired ? "unknown" : scalarType(property.type);
  const valueExpr = hasRequired
    ? `(value as ${scalarType(property.type)})`
    : "value";

  const lines = [`// Constraint from ${sourceHint} — ${prop}: ${desc}`];
  lines.push(
    `export function ${fnName}(value: ${valueType}, source: string): void {`,
  );
  for (const constraint of constraints) {
    const message = constraint.kind === "required"
      ? `\`\${source}: ${prop} is required\``
      : `\`\${source}: ${prop} = \${value} violates constraint ${
        describeConstraint(constraint)
      }\``;
    lines.push(`  if (${renderCondition(constraint, valueExpr)}) {`);
    lines.push(`    throw new Error(${message});`);
    lines.push(`  }`);
  }
  lines.push(`}`);
  return lines.join("\n");
}

function renderValidate(modelName: string, calls: string[]): string {
  return [
    `/** Run all assertions for ${modelName}; returns violation messages (empty when clean). */`,
    `export function validate${modelName}(value: ${modelName}): string[] {`,
    `  const violations: string[] = [];`,
    ...calls,
    `  return violations;`,
    `}`,
  ].join("\n");
}

// --- Constraint → condition / message ---

function renderCondition(constraint: Constraint, valueExpr: string): string {
  switch (constraint.kind) {
    case "range": {
      const min = constraint.min;
      const max = constraint.max;
      if (min !== undefined && max !== undefined) {
        return `${valueExpr} < ${min} || ${valueExpr} > ${max}`;
      }
      if (min !== undefined) return `${valueExpr} < ${min}`;
      if (max !== undefined) return `${valueExpr} > ${max}`;
      return "false";
    }
    case "minimum":
      return `${valueExpr} < ${constraint.value ?? "Number.NEGATIVE_INFINITY"}`;
    case "maximum":
      return `${valueExpr} > ${constraint.value ?? "Number.POSITIVE_INFINITY"}`;
    case "positive":
      return `${valueExpr} <= 0`;
    case "required":
      return "value === undefined || value === null";
    case "format":
      return `${valueExpr}.trim() === ""`;
    case "enum": {
      const values = constraint.values ?? [];
      return `!(${JSON.stringify(values)} as ${
        enumCast(values)
      }).includes(${valueExpr})`;
    }
    default:
      return "false";
  }
}

function describeConstraint(constraint: Constraint): string {
  switch (constraint.kind) {
    case "range": {
      const min = constraint.min;
      const max = constraint.max;
      if (min !== undefined && max !== undefined) return `[${min}..${max}]`;
      if (min !== undefined) return `[${min}..]`;
      if (max !== undefined) return `[..${max}]`;
      return "range";
    }
    case "minimum":
      return `>= ${constraint.value ?? "?"}`;
    case "maximum":
      return `<= ${constraint.value ?? "?"}`;
    case "positive":
      return "> 0";
    case "required":
      return "required";
    case "format":
      return `format ${constraint.value ?? "unknown"}`;
    case "enum": {
      const values = (constraint.values ?? []).map((v) => JSON.stringify(v));
      return `[${values.join(",")}]`;
    }
    default:
      return constraint.kind;
  }
}

// --- Type plumbing ---

/** The scalar TS type the value parameter is asserted against. */
function scalarType(type: string): string {
  if (type === "string" || type === "number" || type === "boolean") return type;
  return "unknown";
}

/** Constraints we can assert without violating type-safety. Numeric and
 * format/enum constraints only apply to scalar `string`/`number` properties;
 * `required` works on any property (checked through `unknown`). */
function applicableConstraints(property: Property): Constraint[] {
  return (property.constraints ?? []).filter((c) => {
    switch (c.kind) {
      case "required":
        return true;
      case "range":
      case "minimum":
      case "maximum":
      case "positive":
        return property.type === "number";
      case "enum":
        return property.type === "string" || property.type === "number";
      case "format":
        return property.type === "string";
      default:
        return false;
    }
  });
}

function enumCast(values: (string | number)[]): string {
  if (values.every((v) => typeof v === "number")) return "number[]";
  if (values.every((v) => typeof v === "string")) return "string[]";
  return "(string | number)[]";
}
