import { assertEquals, assertStringIncludes } from "@std/assert";

import type { ExtractedSpec } from "../extract/types.ts";
import { generateAssertions } from "./assertions.ts";

// The classroom fixture from README/DESIGN §7.1, with its extracted constraints.
const classroom: ExtractedSpec = {
  models: [
    {
      name: "Student",
      source: "models/student.md",
      properties: [
        { name: "name", type: "string" },
        {
          name: "email",
          type: "string",
          constraints: [{ kind: "format", value: "email" }],
        },
        {
          name: "gradeLevel",
          type: "number",
          constraints: [{ kind: "range", min: 9, max: 12 }],
        },
        { name: "enrollmentDate", type: "date" },
      ],
    },
    {
      name: "Teacher",
      source: "models/teacher.md",
      properties: [
        { name: "name", type: "string" },
        {
          name: "email",
          type: "string",
          constraints: [{ kind: "format", value: "email" }],
        },
        { name: "department", type: "string" },
        { name: "hireDate", type: "date" },
      ],
    },
    {
      name: "Class",
      source: "models/class.md",
      properties: [
        { name: "name", type: "string" },
        { name: "subject", type: "string" },
        { name: "room", type: "string" },
        {
          name: "maxStudents",
          type: "number",
          constraints: [{ kind: "range", min: 1, max: 30 }],
        },
      ],
    },
  ],
};

Deno.test("generateAssertions emits assert + validate functions for the classroom spec", () => {
  const out = generateAssertions(classroom);

  assertStringIncludes(
    out,
    "// .verbo/validate.ts — generated by Verbo, do not edit.",
  );
  assertStringIncludes(
    out,
    'import type { Student, Teacher, Class } from "../types.verbo.ts";',
  );

  // DESIGN §8.2: the exact gradeLevel range assertion.
  assertStringIncludes(
    out,
    "export function assert_Student_gradeLevel(value: number, source: string): void {",
  );
  assertStringIncludes(out, "  if (value < 9 || value > 12) {");
  assertStringIncludes(
    out,
    "    throw new Error(`${source}: gradeLevel = ${value} violates constraint [9..12]`);",
  );

  assertStringIncludes(
    out,
    "export function assert_Class_maxStudents(value: number, source: string): void {",
  );
  assertStringIncludes(
    out,
    "export function validateClass(value: Class): string[] {",
  );
  assertStringIncludes(
    out,
    '  run(() => assert_Class_maxStudents(value.maxStudents, "Class.maxStudents"), violations);',
  );
});

Deno.test("generateAssertions merges multiple constraints into one assert function", () => {
  const spec: ExtractedSpec = {
    models: [{
      name: "Todo",
      source: "models/todo.md",
      properties: [
        {
          name: "status",
          type: "string",
          constraints: [{ kind: "enum", values: ["active", "completed"] }],
        },
        {
          name: "notes",
          type: "string",
          optional: true,
          constraints: [{ kind: "format", value: "url" }],
        },
        {
          name: "priority",
          type: "number",
          constraints: [{ kind: "minimum", value: 1 }, { kind: "positive" }],
        },
      ],
    }],
  };

  const out = generateAssertions(spec);

  // One merged function for `minimum` + `positive` — no duplicate declaration.
  assertEquals(out.match(/export function assert_Todo_priority/g)?.length, 1);
  assertStringIncludes(
    out,
    "// Constraint from models/todo.md — priority: >= 1, > 0",
  );
  assertStringIncludes(out, "  if (value < 1) {");
  assertStringIncludes(out, "  if (value <= 0) {");

  // enum + optional format
  assertStringIncludes(
    out,
    '  if (!(["active","completed"] as string[]).includes(value)) {',
  );
  assertStringIncludes(out, "  if (value.notes !== undefined) {");
  assertStringIncludes(
    out,
    '    run(() => assert_Todo_notes(value.notes, "Todo.notes"), violations);',
  );
});

Deno.test("generateAssertions types required through unknown and merges with typed checks", () => {
  const spec: ExtractedSpec = {
    models: [{
      name: "User",
      source: "models/user.md",
      properties: [
        { name: "name", type: "string", constraints: [{ kind: "required" }] },
        {
          name: "email",
          type: "string",
          constraints: [{ kind: "required" }, {
            kind: "format",
            value: "email",
          }],
        },
      ],
    }],
  };

  const out = generateAssertions(spec);

  assertStringIncludes(
    out,
    "export function assert_User_name(value: unknown, source: string): void {",
  );
  assertStringIncludes(
    out,
    "    throw new Error(`${source}: name is required`);",
  );
  // required + format share one function: the typed check casts through unknown.
  assertStringIncludes(
    out,
    "export function assert_User_email(value: unknown, source: string): void {",
  );
  assertStringIncludes(out, "  if (value === undefined || value === null) {");
  assertStringIncludes(
    out,
    "    throw new Error(`${source}: email is required`);",
  );
  assertStringIncludes(out, '  if ((value as string).trim() === "") {');
});

Deno.test("generateAssertions skips constraints incompatible with the property type", () => {
  const spec: ExtractedSpec = {
    models: [{
      name: "Mixed",
      source: "models/mixed.md",
      properties: [
        // range on an array → not asserted (would not type-check)
        {
          name: "rating",
          type: "number[]",
          constraints: [{ kind: "range", min: 0, max: 5 }],
        },
        // format on a boolean → not asserted
        {
          name: "ok",
          type: "boolean",
          constraints: [{ kind: "format", value: "email" }],
        },
        // enum on a boolean → not asserted
        {
          name: "flag",
          type: "boolean",
          constraints: [{ kind: "enum", values: ["on", "off"] }],
        },
        // positive on a date → not asserted
        { name: "when", type: "date", constraints: [{ kind: "positive" }] },
        // required always applies
        { name: "label", type: "string", constraints: [{ kind: "required" }] },
      ],
    }],
  };

  const out = generateAssertions(spec);
  assertStringIncludes(out, "assert_Mixed_label");
  assertEquals(out.includes("assert_Mixed_rating"), false);
  assertEquals(out.includes("assert_Mixed_ok"), false);
  assertEquals(out.includes("assert_Mixed_flag"), false);
  assertEquals(out.includes("assert_Mixed_when"), false);
});

Deno.test("generateAssertions emits only the header for specs without constraints", () => {
  const spec: ExtractedSpec = {
    models: [{
      name: "Empty",
      source: "models/empty.md",
      properties: [{ name: "name", type: "string" }],
    }],
  };

  const out = generateAssertions(spec);
  assertEquals(
    out,
    "// .verbo/validate.ts — generated by Verbo, do not edit.\n",
  );
});

Deno.test("generateAssertions output type-checks against its generated types", async () => {
  // Integration: write types.verbo.ts + .verbo/validate.ts to a temp project and
  // run `deno check` on the assertions module. Needs the `run` test permission
  // (provided by `./dev test`, which passes `-P`).
  const dir = Deno.makeTempDirSync({ prefix: "verbo-assertions-test-" });
  try {
    Deno.writeTextFileSync(
      `${dir}/types.verbo.ts`,
      [
        "export type Student = { name: string; email: string; gradeLevel: number; enrollmentDate: Date; classes: Class[] };",
        "export type Teacher = { name: string; email: string; department: string; hireDate: Date; classes: Class[] };",
        "export type Class = { name: string; subject: string; room: string; maxStudents: number; teacher: Teacher; students: Student[] };",
      ].join("\n"),
    );
    Deno.mkdirSync(`${dir}/.verbo`, { recursive: true });
    Deno.writeTextFileSync(
      `${dir}/.verbo/validate.ts`,
      generateAssertions(classroom),
    );

    const cmd = new Deno.Command("deno", {
      args: ["check", `${dir}/.verbo/validate.ts`],
      stdout: "piped",
      stderr: "piped",
    });
    const result = await cmd.output();
    const stderr = new TextDecoder().decode(result.stderr);
    assertEquals(result.success, true, stderr);
  } finally {
    Deno.removeSync(dir, { recursive: true });
  }
});
