import { assertEquals, assertStringIncludes } from "@std/assert";

import type { ExtractedSpec } from "../extract/types.ts";
import { generateTypes } from "./types.ts";

// The classroom fixture from README/DESIGN §7.1.
const classroom: ExtractedSpec = {
  models: [
    {
      name: "Student",
      source: "models/student.md",
      properties: [
        { name: "name", type: "string" },
        {
          name: "email",
          type: "string",
          constraints: [{ kind: "format", value: "email" }],
        },
        {
          name: "gradeLevel",
          type: "number",
          constraints: [{ kind: "range", min: 9, max: 12 }],
        },
        { name: "enrollmentDate", type: "date" },
        { name: "classes", type: "Class[]" },
      ],
    },
    {
      name: "Teacher",
      source: "models/teacher.md",
      properties: [
        { name: "name", type: "string" },
        {
          name: "email",
          type: "string",
          constraints: [{ kind: "format", value: "email" }],
        },
        { name: "department", type: "string" },
        { name: "hireDate", type: "date" },
        { name: "classes", type: "Class[]" },
      ],
    },
    {
      name: "Class",
      source: "models/class.md",
      properties: [
        { name: "name", type: "string" },
        { name: "subject", type: "string" },
        { name: "room", type: "string" },
        {
          name: "maxStudents",
          type: "number",
          constraints: [{ kind: "range", min: 1, max: 30 }],
        },
        { name: "teacher", type: "Teacher" },
        { name: "students", type: "Student[]" },
      ],
    },
  ],
};

Deno.test("generateTypes renders the classroom spec exactly like DESIGN §7.1", () => {
  const expected = [
    "// Generated by Verbo — do not edit directly.",
    "// Source: models/student.md, models/teacher.md, models/class.md",
    "",
    "export type Student = {",
    "  name: string;",
    "  email: string;",
    "  gradeLevel: number;",
    "  enrollmentDate: Date;",
    "  classes: Class[];",
    "};",
    "",
    "export type Teacher = {",
    "  name: string;",
    "  email: string;",
    "  department: string;",
    "  hireDate: Date;",
    "  classes: Class[];",
    "};",
    "",
    "export type Class = {",
    "  name: string;",
    "  subject: string;",
    "  room: string;",
    "  maxStudents: number;",
    "  teacher: Teacher;",
    "  students: Student[];",
    "};",
  ].join("\n") + "\n";

  assertEquals(generateTypes(classroom), expected);
});
Deno.test("generateTypes emits enum unions, optional, arrays and model refs", () => {
  const spec: ExtractedSpec = {
    models: [
      {
        name: "Todo",
        properties: [
          { name: "name", type: "string" },
          {
            name: "status",
            type: "string",
            constraints: [{ kind: "enum", values: ["active", "completed"] }],
          },
          { name: "tags", type: "string[]" },
          { name: "dueAt", type: "date" },
          { name: "assignee", type: "User" },
          { name: "notes", type: "string", optional: true },
          { name: "rating", type: "number[]" },
        ],
      },
      {
        name: "User",
        source: "models/user.md",
        properties: [{ name: "email", type: "string" }],
      },
    ],
  };

  const expected = [
    "// Generated by Verbo — do not edit directly.",
    "// Source: models/user.md",
    "",
    'export type TodoStatus = "active" | "completed";',
    "",
    "export type Todo = {",
    "  name: string;",
    "  status: TodoStatus;",
    "  tags: string[];",
    "  dueAt: Date;",
    "  assignee: User;",
    "  notes?: string;",
    "  rating: number[];",
    "};",
    "",
    "export type User = {",
    "  email: string;",
    "};",
  ].join("\n") + "\n";

  assertEquals(generateTypes(spec), expected);
});

Deno.test("generateTypes renders model-reference properties as T / T[] fields", () => {
  const spec: ExtractedSpec = {
    models: [
      {
        name: "Class",
        properties: [
          { name: "students", type: "Student[]" },
          { name: "teacher", type: "Teacher" },
          { name: "monsters", type: "Monster[]" },
          { name: "syllabus", type: "Syllabus" },
        ],
      },
    ],
  };

  const expected = [
    "// Generated by Verbo — do not edit directly.",
    "",
    "export type Class = {",
    "  students: Student[];",
    "  teacher: Teacher;",
    "  monsters: Monster[];",
    "  syllabus: Syllabus;",
    "};",
  ].join("\n") + "\n";

  assertEquals(generateTypes(spec), expected);
});

Deno.test("generateTypes handles empty models, numeric enums and escaping", () => {
  const spec: ExtractedSpec = {
    models: [
      { name: "Empty", properties: [] },
      {
        name: "Score",
        source: "models/score.md",
        properties: [
          {
            name: "level",
            type: "number",
            constraints: [{ kind: "enum", values: [1, 2, 3] }],
          },
          {
            name: "label",
            type: "string",
            constraints: [{ kind: "enum", values: ['a"b', "c"] }],
          },
          { name: "history", type: "date[]" },
        ],
      },
    ],
  };

  const expected = [
    "// Generated by Verbo — do not edit directly.",
    "// Source: models/score.md",
    "",
    "export type ScoreLevel = 1 | 2 | 3;",
    "",
    'export type ScoreLabel = "a\\"b" | "c";',
    "",
    "export type Empty = {};",
    "",
    "export type Score = {",
    "  level: ScoreLevel;",
    "  label: ScoreLabel;",
    "  history: Date[];",
    "};",
  ].join("\n") + "\n";

  assertEquals(generateTypes(spec), expected);
});

// H1 regression: an enum constraint on a non-scalar property must NOT swap the
// property's type for the enum union. `string[]` keeps `string[]`, `number[]`
// keeps `number[]`, a model reference keeps the reference — and no dangling
// union type is emitted. The assertion generator skips non-scalar enums too
// (shared `enumApplies` in src/generator/constraints.ts), so both agree.
Deno.test("generateTypes keeps the element type on enum-constrained arrays and refs (H1)", () => {
  const spec: ExtractedSpec = {
    models: [{
      name: "Todo",
      properties: [
        {
          name: "tags",
          type: "string[]",
          constraints: [{ kind: "enum", values: ["urgent", "later"] }],
        },
        {
          name: "ratings",
          type: "number[]",
          constraints: [{ kind: "enum", values: [1, 2, 3] }],
        },
        {
          name: "owner",
          type: "User",
          constraints: [{ kind: "enum", values: ["a"] }],
        },
        // A scalar enum must still produce its union.
        {
          name: "status",
          type: "string",
          constraints: [{ kind: "enum", values: ["active", "completed"] }],
        },
      ],
    }],
  };

  const out = generateTypes(spec);
  assertStringIncludes(out, 'export type TodoStatus = "active" | "completed";');
  // No union types may be emitted for the array/reference properties.
  assertEquals(out.includes("TodoTags"), false);
  assertEquals(out.includes("TodoRatings"), false);
  assertEquals(out.includes("TodoOwner"), false);
  // Element/reference types are preserved verbatim.
  assertStringIncludes(out, "  tags: string[];");
  assertStringIncludes(out, "  ratings: number[];");
  assertStringIncludes(out, "  owner: User;");
});

// H1 integration: the enum-on-array output must be valid TS that `deno check`
// accepts. Needs the `run` test permission (provided by `./dev test` / `-P`).
Deno.test("generateTypes enum-on-array output passes deno check (H1)", async () => {
  const spec: ExtractedSpec = {
    models: [{
      name: "Todo",
      properties: [
        {
          name: "tags",
          type: "string[]",
          constraints: [{ kind: "enum", values: ["urgent", "later"] }],
        },
        {
          name: "status",
          type: "string",
          constraints: [{ kind: "enum", values: ["active", "completed"] }],
        },
      ],
    }],
  };

  const dir = Deno.makeTempDirSync({ prefix: "verbo-types-enum-array-" });
  try {
    Deno.writeTextFileSync(`${dir}/types.verbo.ts`, generateTypes(spec));
    const cmd = new Deno.Command("deno", {
      args: ["check", `${dir}/types.verbo.ts`],
      stdout: "piped",
      stderr: "piped",
    });
    const result = await cmd.output();
    const stderr = new TextDecoder().decode(result.stderr);
    assertEquals(result.success, true, stderr);
  } finally {
    Deno.removeSync(dir, { recursive: true });
  }
});

// --- Functions ---

Deno.test("generateTypes renders function contracts after the models", () => {
  const spec: ExtractedSpec = {
    models: [
      {
        name: "Entry",
        source: "models/entry.md",
        properties: [{ name: "name", type: "string" }],
      },
    ],
    functions: [
      {
        name: "formatSize",
        source: "functions.md",
        params: [{ name: "bytes", type: "number" }],
        returnType: "string",
      },
      {
        name: "logEntry",
        params: [{ name: "entry", type: "Entry" }],
        returnType: "void",
      },
      {
        name: "round",
        params: [
          { name: "value", type: "number" },
          { name: "precision", type: "number", optional: true },
        ],
        returnType: "number",
      },
      {
        name: "now",
        params: [],
        returnType: "date",
      },
    ],
  };

  const expected = [
    "// Generated by Verbo — do not edit directly.",
    "// Source: models/entry.md, functions.md",
    "",
    "export type Entry = {",
    "  name: string;",
    "};",
    "",
    "export type formatSize = (bytes: number) => string;",
    "",
    "export type logEntry = (entry: Entry) => void;",
    "",
    "export type round = (value: number, precision?: number) => number;",
    "",
    "export type now = () => Date;",
  ].join("\n") + "\n";

  assertEquals(generateTypes(spec), expected);
});

// Function contracts referencing models must produce valid TS that `deno check`
// accepts — the model types and function types are verified together.
Deno.test("generateTypes function output passes deno check", async () => {
  const spec: ExtractedSpec = {
    models: [
      {
        name: "Class",
        properties: [{ name: "name", type: "string" }],
      },
    ],
    functions: [
      {
        name: "averageClassSize",
        params: [{ name: "classes", type: "Class[]" }],
        returnType: "number",
      },
    ],
  };

  const dir = Deno.makeTempDirSync({ prefix: "verbo-types-functions-" });
  try {
    Deno.writeTextFileSync(`${dir}/types.verbo.ts`, generateTypes(spec));
    const cmd = new Deno.Command("deno", {
      args: ["check", `${dir}/types.verbo.ts`],
      stdout: "piped",
      stderr: "piped",
    });
    const result = await cmd.output();
    const stderr = new TextDecoder().decode(result.stderr);
    assertEquals(result.success, true, stderr);
  } finally {
    Deno.removeSync(dir, { recursive: true });
  }
});
