import type {
  ExtractedSpec,
  Model,
  Property,
  SpecFunction,
} from "../extract/types.ts";
import { enumApplies } from "./constraints.ts";

/**
 * Pure type generator — turns an extracted spec into the text of
 * `types.verbo.ts`, which `deno check` validates (DESIGN §7).
 *
 * Mapping rules:
 * - `date` → `Date`; primitives as-is; model refs → direct; `X[]` → `X[]`
 * - `enum` constraint on a scalar `string`/`number` property → a
 *   `type X = "a" | "b";` union, referenced by the field; on arrays or model
 *   references the enum is skipped and the element/reference type is kept
 *   (a union would swallow the `[]` — see docs/tasks.md H1)
 * - `optional` → `?`
 * - a model reference property → that model's type (`Teacher`), or an array of
 *   references → `T[]` (`Class[]`)
 * - a function → a function type contract `export type name = (params) => R;`
 *   (DESIGN §1: contracts only — no implementation is generated)
 */

const HEADER = "// Generated by Verbo — do not edit directly.";

export function generateTypes(spec: ExtractedSpec): string {
  const sections: string[] = [];

  // Enum-constraint unions first, then the models (types are hoisted, so
  // declaration order within the file is free).
  for (const model of spec.models) {
    for (const property of model.properties) {
      const values = enumValues(property);
      if (values && values.length > 0) {
        sections.push(
          renderEnumType(enumTypeName(model.name, property.name), values),
        );
      }
    }
  }

  for (const model of spec.models) {
    sections.push(renderModel(model));
  }

  // Function contracts last — they may reference the model types above (types
  // are hoisted, so declaration order is free either way).
  for (const fn of spec.functions ?? []) {
    sections.push(renderFunction(fn));
  }

  return `${buildHeader(spec)}\n\n${sections.join("\n\n")}\n`;
}

function buildHeader(spec: ExtractedSpec): string {
  const sources: string[] = [];
  for (const model of spec.models) {
    if (model.source && !sources.includes(model.source)) {
      sources.push(model.source);
    }
  }
  for (const fn of spec.functions ?? []) {
    if (fn.source && !sources.includes(fn.source)) {
      sources.push(fn.source);
    }
  }
  return sources.length > 0
    ? `${HEADER}\n// Source: ${sources.join(", ")}`
    : HEADER;
}

// --- Type mapping ---

function mapType(type: string): string {
  if (type.endsWith("[]")) {
    return `${mapType(type.slice(0, -2))}[]`;
  }
  switch (type) {
    case "date":
      return "Date";
    case "string":
    case "number":
    case "boolean":
      return type;
    default:
      // Anything else is a model reference (or an unknown type, which
      // `deno check` will flag and the repair loop will correct).
      return type;
  }
}

// --- Enums ---

function enumValues(property: Property): (string | number)[] | undefined {
  // Enum unions only apply to scalar string/number properties (H1). On array
  // or model-reference types the union would replace `string[]` / `Teacher`
  // with a single union type; both generators skip non-scalar enums via the
  // shared `enumApplies` predicate so they can never drift again.
  if (!enumApplies(property)) return undefined;
  return property.constraints?.find((c) => c.kind === "enum")?.values;
}

function enumTypeName(modelName: string, propertyName: string): string {
  const base = propertyName.charAt(0).toUpperCase() + propertyName.slice(1);
  return `${modelName}${base}`;
}

function renderEnumType(name: string, values: (string | number)[]): string {
  const members = values.map((v) =>
    typeof v === "number" ? String(v) : JSON.stringify(v)
  );
  return `export type ${name} = ${members.join(" | ")};`;
}

// --- Models ---

function renderModel(model: Model): string {
  const lines: string[] = [];

  for (const property of model.properties) {
    const values = enumValues(property);
    const type = values && values.length > 0
      ? enumTypeName(model.name, property.name)
      : mapType(property.type);
    const optional = property.optional ? "?" : "";
    lines.push(`  ${property.name}${optional}: ${type};`);
  }

  const body = lines.length > 0 ? `\n${lines.join("\n")}\n` : "";
  return `export type ${model.name} = {${body}};`;
}

// --- Functions ---

function renderFunction(fn: SpecFunction): string {
  const params = fn.params.map((p) => {
    const optional = p.optional ? "?" : "";
    return `${p.name}${optional}: ${mapType(p.type)}`;
  });
  return `export type ${fn.name} = (${params.join(", ")}) => ${
    mapType(fn.returnType)
  };`;
}
