import { assertEquals } from "@std/assert";

import type { ExtractedSpec } from "../extract/types.ts";
import { generateTypes } from "./types.ts";

// The classroom fixture from README/DESIGN §7.1.
const classroom: ExtractedSpec = {
  models: [
    {
      name: "Student",
      source: "models/student.md",
      properties: [
        { name: "name", type: "string" },
        {
          name: "email",
          type: "string",
          constraints: [{ kind: "format", value: "email" }],
        },
        {
          name: "gradeLevel",
          type: "number",
          constraints: [{ kind: "range", min: 9, max: 12 }],
        },
        { name: "enrollmentDate", type: "date" },
        { name: "classes", type: "Class[]" },
      ],
    },
    {
      name: "Teacher",
      source: "models/teacher.md",
      properties: [
        { name: "name", type: "string" },
        {
          name: "email",
          type: "string",
          constraints: [{ kind: "format", value: "email" }],
        },
        { name: "department", type: "string" },
        { name: "hireDate", type: "date" },
        { name: "classes", type: "Class[]" },
      ],
    },
    {
      name: "Class",
      source: "models/class.md",
      properties: [
        { name: "name", type: "string" },
        { name: "subject", type: "string" },
        { name: "room", type: "string" },
        {
          name: "maxStudents",
          type: "number",
          constraints: [{ kind: "range", min: 1, max: 30 }],
        },
        { name: "teacher", type: "Teacher" },
        { name: "students", type: "Student[]" },
      ],
    },
  ],
};

Deno.test("generateTypes renders the classroom spec exactly like DESIGN §7.1", () => {
  const expected = [
    "// Generated by Verbo — do not edit directly.",
    "// Source: models/student.md, models/teacher.md, models/class.md",
    "",
    "export type Student = {",
    "  name: string;",
    "  email: string;",
    "  gradeLevel: number;",
    "  enrollmentDate: Date;",
    "  classes: Class[];",
    "};",
    "",
    "export type Teacher = {",
    "  name: string;",
    "  email: string;",
    "  department: string;",
    "  hireDate: Date;",
    "  classes: Class[];",
    "};",
    "",
    "export type Class = {",
    "  name: string;",
    "  subject: string;",
    "  room: string;",
    "  maxStudents: number;",
    "  teacher: Teacher;",
    "  students: Student[];",
    "};",
  ].join("\n") + "\n";

  assertEquals(generateTypes(classroom), expected);
});
Deno.test("generateTypes emits enum unions, optional, arrays and model refs", () => {
  const spec: ExtractedSpec = {
    models: [
      {
        name: "Todo",
        properties: [
          { name: "name", type: "string" },
          {
            name: "status",
            type: "string",
            constraints: [{ kind: "enum", values: ["active", "completed"] }],
          },
          { name: "tags", type: "string[]" },
          { name: "dueAt", type: "date" },
          { name: "assignee", type: "User" },
          { name: "notes", type: "string", optional: true },
          { name: "rating", type: "number[]" },
        ],
      },
      {
        name: "User",
        source: "models/user.md",
        properties: [{ name: "email", type: "string" }],
      },
    ],
  };

  const expected = [
    "// Generated by Verbo — do not edit directly.",
    "// Source: models/user.md",
    "",
    'export type TodoStatus = "active" | "completed";',
    "",
    "export type Todo = {",
    "  name: string;",
    "  status: TodoStatus;",
    "  tags: string[];",
    "  dueAt: Date;",
    "  assignee: User;",
    "  notes?: string;",
    "  rating: number[];",
    "};",
    "",
    "export type User = {",
    "  email: string;",
    "};",
  ].join("\n") + "\n";

  assertEquals(generateTypes(spec), expected);
});

Deno.test("generateTypes renders model-reference properties as T / T[] fields", () => {
  const spec: ExtractedSpec = {
    models: [
      {
        name: "Class",
        properties: [
          { name: "students", type: "Student[]" },
          { name: "teacher", type: "Teacher" },
          { name: "monsters", type: "Monster[]" },
          { name: "syllabus", type: "Syllabus" },
        ],
      },
    ],
  };

  const expected = [
    "// Generated by Verbo — do not edit directly.",
    "",
    "export type Class = {",
    "  students: Student[];",
    "  teacher: Teacher;",
    "  monsters: Monster[];",
    "  syllabus: Syllabus;",
    "};",
  ].join("\n") + "\n";

  assertEquals(generateTypes(spec), expected);
});

Deno.test("generateTypes handles empty models, numeric enums and escaping", () => {
  const spec: ExtractedSpec = {
    models: [
      { name: "Empty", properties: [] },
      {
        name: "Score",
        source: "models/score.md",
        properties: [
          {
            name: "level",
            type: "number",
            constraints: [{ kind: "enum", values: [1, 2, 3] }],
          },
          {
            name: "label",
            type: "string",
            constraints: [{ kind: "enum", values: ["a\"b", "c"] }],
          },
          { name: "history", type: "date[]" },
        ],
      },
    ],
  };

  const expected = [
    "// Generated by Verbo — do not edit directly.",
    "// Source: models/score.md",
    "",
    "export type ScoreLevel = 1 | 2 | 3;",
    "",
    'export type ScoreLabel = "a\\"b" | "c";',
    "",
    "export type Empty = {};",
    "",
    "export type Score = {",
    "  level: ScoreLevel;",
    "  label: ScoreLabel;",
    "  history: Date[];",
    "};",
  ].join("\n") + "\n";

  assertEquals(generateTypes(spec), expected);
});

