name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - run: | 
        npm ci
        npm run build --if-present
    - name: 'Test generation'
    - run: |
        touch .env
        echo GEMINI_KEY=${{ secrets.GEMINI_KEY }} >> .env
        make test-gemini
